# Generated by Django 5.0.14 on 2025-05-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('dojos', '0003_alter_dojo_create_at_alter_dojo_update_at'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='pago',
            name='dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojos.dojo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
