# Generated by Django 5.0.14 on 2025-05-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_alter_dojo_create_at_alter_dojo_update_at'),
        ('pagos', '0002_remove_pago_confirmado_pago_dojo_alter_pago_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.dojo'),
        ),
    ]
