# Generated by Django 5.0.14 on 2025-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_dojo_create_at_dojo_estado_dojo_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
