# Generated by Django 5.0.14 on 2025-05-03 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_create_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
