# Generated by Django 5.0.14 on 2025-05-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_examen_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='pago',
            new_name='monto_pago',
        ),
    ]
